services:
  springbootapp:
    build: .
    ports:
    - "8080:8080"
  prometheus:
    image: prom/prometheus
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus:/etc/prometheus
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
    - springbootapp
  grafana:
    image: grafana/grafana
    depends_on:
    - prometheus
    ports:
    - 3000:3000